# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-02 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0014_auto_20170117_0845")]

    operations = [
        migrations.CreateModel(
            name="NewCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("lft", models.PositiveIntegerField(db_index=True, editable=False)),
                ("rght", models.PositiveIntegerField(db_index=True, editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(db_index=True, editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="api.NewCategory",
                    ),
                ),
            ],
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category (old)", "verbose_name_plural": "categories (old)"},
        ),
        migrations.AlterField(
            model_name="resource",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="resources", to="api.Category"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="keywords",
            field=models.ManyToManyField(blank=True, related_name="resources", to="api.Keyword"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="published",
            field=models.DateField(
                help_text="ISO 8601 format, e.g., 1946-07-06.", verbose_name="publication date"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CATALOG", "Database or catalog"),
                    ("LEGAL_DOCUMENT", "Government report or legal document"),
                    ("MAGAZINE_ARTICLE", "Magazine article"),
                    ("JOURNAL_ARTICLE", "Journal article"),
                    ("PRESENTATION", "Presentation"),
                    ("STUDY_REPORT", "Project or study report"),
                    ("SCHOLARLY_BOOK", "Scholarly book"),
                    ("TEXTBOOK", "Textbook"),
                    ("THESIS", "Thesis or dissertation"),
                    ("WEBSITE", "Website"),
                    ("WORKING_PAPER", "Working paper"),
                    ("RESEARCH_SUMMARY", "Literature review"),
                    ("METASTUDY", "Meta-analysis"),
                    ("OPINION_PIECE", "Opinion piece"),
                    ("HISTORICAL_DOCUMENT", "Historical document"),
                    ("ENCYCLOPEDIA_ARTICLE", "Encyclopedia entry"),
                    ("BOOK", "Nonfiction book"),
                    ("NEWS_ARTICLE", "Newspaper article"),
                    ("BLOG_ARTICLE", "Blog post"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="newcategories",
            field=mptt.fields.TreeManyToManyField(
                blank=True, related_name="resources", to="api.NewCategory"
            ),
        ),
    ]
