# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-02 12:56
from __future__ import unicode_literals

from django.db import migrations

from .. import fields


def migrate_published(apps, schema_editor):
    Resource = apps.get_model("api", "Resource")
    for resource in Resource.objects.all():
        resource.approx_published = resource.published.strftime("%Y-%m-%d")
        resource.save()


class Migration(migrations.Migration):

    dependencies = [("api", "0015_auto_20200102_1253")]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="approx_published",
            field=fields.ApproximateDateField(
                default="1000-01-01",
                help_text="Formats YYYY-MM-DD, YYYY-MM, and YYYY.",
                verbose_name="approx. publication date",
            ),
        ),
        migrations.RunPython(migrate_published),
    ]
