# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-02 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0016_resource_approx_published")]

    operations = [
        migrations.RemoveField(model_name="resource", name="published"),
        migrations.RenameField(
            model_name="resource", old_name="approx_published", new_name="published"
        ),
    ]
