# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-04 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0017_auto_20200102_1424")]

    operations = [
        migrations.RemoveField(model_name="resource", name="categories"),
        migrations.DeleteModel("Category"),
        migrations.RenameModel("NewCategory", "Category"),
        migrations.RenameField(
            model_name="resource", old_name="newcategories", new_name="categories"
        ),
        migrations.RunSQL(
            "alter sequence api_newcategory_id_seq rename to api_category_id_seq;",
            "alter sequence api_category_id_seq rename to api_newcategory_id_seq;",
        ),
        migrations.RunSQL(
            "alter sequence api_resource_newcategories_id_seq rename to api_resource_categories_id_seq;",
            "alter sequence api_resource_categories_id_seq rename to api_resource_newcategories_id_seq;",
        ),
    ]
