# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-23 19:31
from __future__ import unicode_literals

import django.db.models
from django.db import migrations, models
import django.utils.timezone
import researchlibrary.api.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_old_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resource",
            name="misc",
            field=django.db.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="resource",
            name="published",
            field=researchlibrary.api.fields.ApproximateDateField(
                default="1000-01-01",
                help_text="Formats YYYY-MM-DD, YYYY-MM, and YYYY.",
                verbose_name="publication date",
            ),
        ),
    ]
