# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-24 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200423_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
