# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-29 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0020_auto_20200424_1400")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="remote_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="resource",
            name="remote_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLOG_ARTICLE", "Blog post"),
                    ("BOOK", "Nonfiction book"),
                    ("BROADCAST", "Broadcast"),
                    ("CATALOG", "Database or catalog"),
                    ("CHAPTER", "Book chapter"),
                    ("CONFERENCE_ARTICLE", "Conference article"),
                    ("ENCYCLOPEDIA_ARTICLE", "Encyclopedia entry"),
                    ("FILM", "Film or documentary"),
                    ("HISTORICAL_DOCUMENT", "Historical document"),
                    ("JOURNAL_ARTICLE", "Journal article"),
                    ("LEGAL_DOCUMENT", "Government report or legal document"),
                    ("MAGAZINE_ARTICLE", "Magazine article"),
                    ("MANUSCRIPT", "Manuscript"),
                    ("METASTUDY", "Meta-analysis"),
                    ("NEWS_ARTICLE", "Newspaper article"),
                    ("OPINION_PIECE", "Opinion piece"),
                    ("OTHER", "Other"),
                    ("PERSONAL_COMMUNICATION", "Personal communication"),
                    ("PRESENTATION", "Presentation"),
                    ("RESEARCH_SUMMARY", "Literature review"),
                    ("SCHOLARLY_BOOK", "Scholarly book"),
                    ("STUDY_REPORT", "Project or study report"),
                    ("TEXTBOOK", "Textbook"),
                    ("THESIS", "Thesis or dissertation"),
                    ("WEBSITE", "Website"),
                    ("WORKING_PAPER", "Working paper"),
                ],
                max_length=30,
            ),
        ),
    ]
