# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-05 14:27
from __future__ import unicode_literals

from django.db import migrations
import researchlibrary.api.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200429_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='published',
            field=researchlibrary.api.fields.ApproximateDateField(blank=True, help_text='Formats YYYY-MM-DD, YYYY-MM, and YYYY.', null=True, verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('BLOG_ARTICLE', 'Blog post'), ('BOOK', 'Book'), ('BROADCAST', 'Broadcast'), ('CATALOG', 'Database or catalog'), ('CHAPTER', 'Book chapter'), ('CONFERENCE_ARTICLE', 'Conference article'), ('ENCYCLOPEDIA_ARTICLE', 'Encyclopedia entry'), ('FILM', 'Film or documentary'), ('HISTORICAL_DOCUMENT', 'Historical document'), ('JOURNAL_ARTICLE', 'Journal article'), ('LEGAL_DOCUMENT', 'Government report or legal document'), ('MAGAZINE_ARTICLE', 'Magazine article'), ('MANUSCRIPT', 'Manuscript'), ('METASTUDY', 'Meta-analysis'), ('NEWS_ARTICLE', 'Newspaper article'), ('OPINION_PIECE', 'Opinion piece'), ('OTHER', 'Other'), ('PERSONAL_COMMUNICATION', 'Personal communication'), ('PRESENTATION', 'Presentation'), ('RESEARCH_SUMMARY', 'Literature review'), ('SCHOLARLY_BOOK', 'Scholarly book'), ('STUDY_REPORT', 'Project or study report'), ('TEXTBOOK', 'Textbook'), ('THESIS', 'Thesis or dissertation'), ('WEBSITE', 'Website'), ('WORKING_PAPER', 'Working paper')], max_length=30),
        ),
    ]
